# -*- coding: utf-8 -*-
"""TG_Dijkstra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ro0cnh0eSDABqMwM7l9zceXjH6VfdAju
"""

graph = {
    'A': [('B', 2), ('C', 5)],
    'B': [('A', 2), ('C', 1), ('D', 4)],
    'C': [('A', 5), ('B', 1), ('D', 2)],
    'D': [('B', 4), ('C', 2)]
}

contrainte = {
    'A': {'B': 7, 'C': 0},
    'B': {'A': 7, 'C': 0, 'D': 0},
    'C': {'A': 0, 'B': 0, 'D': 0},
    'D': {'B': 0, 'C': 0}
}

source = 'A'
dist = {node: float('inf') for node in graph} #dictionnaire (clé, valeur) où toutes les valeurs sont à l'infini
dist[source] = 0
unvisited = set(graph.keys()) #tableau contenant toutes les clés

while unvisited:
    current = None
    for node in unvisited:
          if current is None or dist[node] < dist[current]:
              current = node

    if dist[current] == float('inf'):
        break
    unvisited.remove(current)

    for neighbor, weight in graph[current]:
        new_dist = dist[current] + weight + contrainte[current][neighbor]
        if new_dist < dist[neighbor]:
            dist[neighbor] = new_dist

print(dist)